version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - /home/drohne/docker/jenkins/jenkins_home:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      dockerfile: Dockerfile
      context: ubuntu
    networks:
      - net
  db_host:
    container_name: db
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - $PWD/mysql_home:/var/lib/mysql   
    networks:
      - net  
networks:
  net:
  
